package com.github.hejcz.cartographers

enum class ErrorCode {
    ALREADY_IN_GAME,
    NICK_CANT_BE_EMPTY,
    ROOM_ID_CANT_BE_EMPTY,
    GAME_NOT_FOUND,
    ROOM_EXISTS,
    NO_SUCH_ROOM,
    GAME_IN_PROGRESS,
    CANT_DRAW_TWICE,
    NO_DRAWING_TO_UNDO,
    GAME_FINISHED,
    EMPTY_SHAPE,
    INVALID_SHAPE,
    INVALID_TERRAIN_TYPE,
    SHAPE_OUTSIDE_THE_MAP_OR_OVERLAPING,
    SHAPE_MUST_BE_ON_RUINS,
    NICK_TAKEN,
    GAME_NOT_STARTED_YET,
    CANT_JOIN
}